Support custom constraint (templates)
plexsystems/konstraint pull request #553
Opened 2024-11-26 22:55 UTC by mrueg

This PR adds support for a custom template to generate constraints and constrainttemplates with. This can be helpful in case you want to generate a helm chart or a different non-structured deployment artifact using konstraint. I've added internal/commands/constrainttemplate_template.tpl and internal/commands/constraint_template.tpl as examples how this could look like.

In addition, this adds sprig/v3 as a dependency to support more functions in the custom document template.

TODO:
* [ ] Complete the custom constaint template to allow reproducing the generated examples (currently matchers are missing)
* [ ] Add documentation

2024-12-03 11:03 UTC, mrueg commented on internal/rego/rego.go
> +func (r Rego) GetAnnotation(name string) (any, error) {
Had to change the signature here due to https://go.dev/src/text/template/funcs.go?s=14790:14826

2024-12-06 13:49 UTC, mrueg commented
@jalseth @jpreese would love to get some feedback on this, if you got some free cycles to spare. :)

2024-12-12 01:28 UTC, mrueg commented
I added a bit of doc to explain when this can be useful. :)

2025-01-20 07:49 UTC, mrueg commented
Policy check is failing due to missing "if", should be fixed with https://github.com/plexsystems/konstraint/pull/564

2025-02-06 19:48 UTC, mrueg commented
@jalseth this includes now a commit that fixes the failing CI due to opa v0 compatibility.

2025-02-09 03:01 UTC, jalseth requested changes
Thanks for the PR! And apologies for the long delay in getting to this.

2025-02-09 03:03 UTC, jalseth commented on internal/commands/create.go
> +		if constraintTemplateCustomTemplateFile != "" {
Please also add some test coverage for the new code.

2025-02-09 07:39 UTC, mrueg commented on internal/commands/constrainttemplate_template.tpl
> +          properties: {{- .AnnotationParameters | toJSON | fromJSON | toIndentYAML 2 | nindent 12 }}
I tried with toIndentYAML directly, unfortunately then it copies in a lot of empty fields, this was the only way to make it work. I assume some some omitempty fields are not set for yaml on the AnnotationParameters or similar?

2025-02-09 07:40 UTC, mrueg commented on internal/commands/create.go
> +func renderTemplate(violation rego.Rego, appliedTemplate []byte, _ *log.Entry) ([]byte, error) {
Good catch, I think I had some logging in that method before for debugging.

2025-02-09 07:48 UTC, mrueg commented on Dockerfile
> +FROM golang:1.23.6-alpine AS build
Done through rebasing. :)

2025-02-09 07:48 UTC, mrueg commented on internal/commands/create.go
> +		if constraintTemplateCustomTemplateFile != "" {
Agreed, I'll move it into it's own and add some tests for it.

2025-02-12 23:31 UTC, mrueg commented on internal/commands/create.go
> +		if constraintTemplateCustomTemplateFile != "" {
I added some tests.

2025-02-13 03:25 UTC, jalseth approved these changes

2025-02-13 03:25 UTC, merged