Remove all punctuation from anchors in policies.md
plexsystems/konstraint pull request #565
Opened 2024-12-17 22:09 UTC by zephyrdb

Punctuation breaks anchor links in Markdown.  This implements the same rule as GitHub.

2025-01-27 12:32 UTC, mrueg approved these changes

2025-02-09 02:49 UTC, jalseth requested changes
Thanks for the PR!

2025-02-09 02:49 UTC, jalseth commented on internal/commands/document.go
> +		punctReplacer := strings.NewReplacer(
Can we add test coverage for this?

2025-02-10 19:52 UTC, zephyrdb commented on internal/commands/document.go
> +		punctReplacer := strings.NewReplacer(
The examples above test it a bit, but I guess I can add a more inclusive test

2025-02-11 00:58 UTC, zephyrdb commented
So uh, I added a test in the form of an example.  Which isn't ideal, but it's the only way to be sure that not only does the code work, the Markdown does what it says on the tin.  I found a number of odd things in the course of that, including the part where the cmd-click in VSCode works on the anchor in the editor, but my Markdown preview plugin doesn't.  GitHub seems to, though, and it's a pretty contrived example to begin with.  I'll do a little more poking around tomorrow just in case.

2025-02-12 20:18 UTC, zephyrdb commented
Ok a bunch more work later, I think this is as thorough as it can possibly be without being unreasonably complicated and time consuming.

2025-02-13 03:11 UTC, jalseth commented on internal/commands/document.go
> +		punctReplacer := strings.NewReplacer(
The examples change shows it working at this point in time. The goal of test coverage is to ensure that when the code changes, this continues to work as expected. It doesn't have to be an exhaustive test, just a simple unit test that makes sure the replacers are being triggered.

2025-02-13 19:08 UTC, zephyrdb commented on internal/commands/document.go
> +		punctReplacer := strings.NewReplacer(
I'm a little confused.  Acceptance.bats ensures that the output remains correct, and there are no Go tests currently on document.go.  Unless I'm missing something.

2025-02-22 21:21 UTC, merged